// @flow

const buildCDNUrl = (px: string, path: string) => `https://static.odycdn.com/emoticons/${px}/${path}`;

const getEmotes = (px: string, multiplier: string) => ({
  ALIEN: buildCDNUrl(px, `Alien${multiplier}.png`),
  ANGRY_2: buildCDNUrl(px, `angry%202${multiplier}.png`),
  ANGRY_3: buildCDNUrl(px, `angry%203${multiplier}.png`),
  ANGRY_4: buildCDNUrl(px, `angry%204${multiplier}.png`),
  ANGRY: buildCDNUrl(px, `angry${multiplier}.png`),
  BLIND: buildCDNUrl(px, `blind${multiplier}.png`),
  BLOCK: buildCDNUrl(px, `block${multiplier}.png`),
  BOMB: buildCDNUrl(px, `bomb${multiplier}.png`),
  BRAIN_CHIP: buildCDNUrl(px, `Brain%20chip${multiplier}.png`),
  CONFIRM: buildCDNUrl(px, `CONFIRM${multiplier}.png`),
  CONFUSED_1: buildCDNUrl(px, `confused-1${multiplier}.png`),
  CONFUSED: buildCDNUrl(px, `confused${multiplier}.png`),
  COOKING_SOMETHING_NICE: buildCDNUrl(px, `cooking%20something%20nice${multiplier}.png`),
  CRY_2: buildCDNUrl(px, `cry%202${multiplier}.png`),
  CRY_3: buildCDNUrl(px, `cry%203${multiplier}.png`),
  CRY_4: buildCDNUrl(px, `cry%204${multiplier}.png`),
  CRY_5: buildCDNUrl(px, `cry%205${multiplier}.png`),
  CRY: buildCDNUrl(px, `cry${multiplier}.png`),
  DOGE: buildCDNUrl(px, `doge${multiplier}.png`),
  DONUT: buildCDNUrl(px, `donut${multiplier}.png`),
  EGGPLANT_WITH_CONDOM: buildCDNUrl(px, `eggplant%20with%20condom${multiplier}.png`),
  EGGPLANT: buildCDNUrl(px, `eggplant${multiplier}.png`),
  FIRE_UP: buildCDNUrl(px, `fire%20up${multiplier}.png`),
  FLAT_EARTH: buildCDNUrl(px, `Flat%20earth${multiplier}.png`),
  FLYING_SAUCER: buildCDNUrl(px, `Flying%20saucer${multiplier}.png`),
  HEART_CHOPPER: buildCDNUrl(px, `heart%20chopper${multiplier}.png`),
  HYPERTROLL: buildCDNUrl(px, `HyperTroll${multiplier}.png`),
  ICE_CREAM: buildCDNUrl(px, `ice%20cream${multiplier}.png`),
  IDK: buildCDNUrl(px, `IDK${multiplier}.png`),
  ILLUMINATI_1: buildCDNUrl(px, `Illuminati-1${multiplier}.png`),
  ILLUMINATI: buildCDNUrl(px, `Illuminati${multiplier}.png`),
  KISS_2: buildCDNUrl(px, `kiss%202${multiplier}.png`),
  KISS: buildCDNUrl(px, `kiss${multiplier}.png`),
  LASER_GUN: buildCDNUrl(px, `laser%20gun${multiplier}.png`),
  LAUGHING_2: buildCDNUrl(px, `Laughing 2${multiplier}.png`),
  LAUGHING: buildCDNUrl(px, `Laughing${multiplier}.png`),
  LOLLIPOP: buildCDNUrl(px, `Lollipop${multiplier}.png`),
  LOVE_2: buildCDNUrl(px, `Love%202${multiplier}.png`),
  LOVE: buildCDNUrl(px, `Love${multiplier}.png`),
  MONSTER: buildCDNUrl(px, `Monster${multiplier}.png`),
  MUSHROOM: buildCDNUrl(px, `mushroom${multiplier}.png`),
  NAIL_IT: buildCDNUrl(px, `Nail%20It${multiplier}.png`),
  NO: buildCDNUrl(px, `NO${multiplier}.png`),
  OUCH: buildCDNUrl(px, `ouch${multiplier}.png`),
  PEACE: buildCDNUrl(px, `peace${multiplier}.png`),
  PIZZA: buildCDNUrl(px, `pizza${multiplier}.png`),
  RABBIT_HOLE: buildCDNUrl(px, `rabbit%20hole${multiplier}.png`),
  RAINBOW_PUKE_1: buildCDNUrl(px, `rainbow%20puke-1${multiplier}.png`),
  RAINBOW_PUKE: buildCDNUrl(px, `rainbow%20puke${multiplier}.png`),
  RESITAS: buildCDNUrl(px, `resitas${multiplier}.png`),
  ROCK: buildCDNUrl(px, `ROCK${multiplier}.png`),
  SAD: buildCDNUrl(px, `sad${multiplier}.png`),
  SALTY: buildCDNUrl(px, `salty${multiplier}.png`),
  SCARY: buildCDNUrl(px, `scary${multiplier}.png`),
  SLEEP: buildCDNUrl(px, `Sleep${multiplier}.png`),
  SLIME_DOWN: buildCDNUrl(px, `slime%20down${multiplier}.png`),
  SMELLY_ROCKS: buildCDNUrl(px, `smelly%20socks${multiplier}.png`),
  SMILE_2: buildCDNUrl(px, `smile%202${multiplier}.png`),
  SMILE: buildCDNUrl(px, `smile${multiplier}.png`),
  SPACE_CHAD: buildCDNUrl(px, `space%20chad${multiplier}.png`),
  SPACE_JULIAN: buildCDNUrl(px, `Space%20Julian${multiplier}.png`),
  SPACE_TOM: buildCDNUrl(px, `space%20Tom${multiplier}.png`),
  SPACE_WOJAK_1: buildCDNUrl(px, `space%20wojak-1${multiplier}.png`),
  SPACE_WOJAK: buildCDNUrl(px, `space%20wojak${multiplier}.png`),
  SPOCK: buildCDNUrl(px, `SPOCK${multiplier}.png`),
  STAR: buildCDNUrl(px, `Star${multiplier}.png`),
  SUNNY_DAY: buildCDNUrl(px, `sunny%20day${multiplier}.png`),
  SURPRISED: buildCDNUrl(px, `surprised${multiplier}.png`),
  SWEET: buildCDNUrl(px, `sweet${multiplier}.png`),
  THINKING_1: buildCDNUrl(px, `thinking-1${multiplier}.png`),
  THINKING: buildCDNUrl(px, `thinking${multiplier}.png`),
  THUMB_DOWN: buildCDNUrl(px, `thumb%20down${multiplier}.png`),
  THUMB_UP_1: buildCDNUrl(px, `thumb%20up-1${multiplier}.png`),
  THUMB_UP: buildCDNUrl(px, `thumb%20up${multiplier}.png`),
  TIN_HAT: buildCDNUrl(px, `tin%20hat${multiplier}.png`),
  TROLL_KING: buildCDNUrl(px, `Troll%20king${multiplier}.png`),
  UFO: buildCDNUrl(px, `ufo${multiplier}.png`),
  WAITING: buildCDNUrl(px, `waiting${multiplier}.png`),
  WHAT: buildCDNUrl(px, `what_${multiplier}.png`),
  WOODO_DOLL: buildCDNUrl(px, `woodo%20doll${multiplier}.png`),
});

export const EMOTES_24px = getEmotes('24%20px', '');
export const EMOTES_36px = getEmotes('36px', '@1.5x');
export const EMOTES_48px = getEmotes('48%20px', '@2x');
export const EMOTES_72px = getEmotes('72%20px', '@3x');
